export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS'
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL'
export const COMPANY_LIST_RESET = 'COMPANY_LIST_RESET'
export const COMPANY_LIST_REQUEST= 'COMPANY_LIST_REQUEST'

export const COMPANY_ADD_DATA = 'COMPANY_ADD_DATA'
export const COMPANY_ADD_FAIL = 'COMPANY_ADD_FAIL'
export const COMPANY_ADD_RESET = 'COMPANY_ADD_RESET'
export const COMPANY_ADD_SUCCESS = 'COMPANY_ADD_SUCCESS'
