export const FILE_LIST_REUQEST = 'FILE_LIST_REUQEST'
export const FILE_LIST_FAIL = 'FILE_LIST_FAIL'
export const FILE_LIST_SUCCESS = 'FILE_LIST_SUCCESS'
export const FILE_LIST_RESET = 'FILE_LIST_RESET'

export const FILE_CREATE_REQUEST = 'FILE_CREATE_REQUEST'
export const FILE_CREATE_SUCCESS = 'FILE_CREATE_SUCCESS'
export const FILE_CREATE_FAIL = 'FILE_CREATE_FAIL'
export const FILE_CREATE_RESET = 'FILE_CREATE_RESET'

